# Generated by Django 5.2.3 on 2025-06-20 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=512)),
                ("company_name", models.CharField(max_length=255)),
                ("company_url", models.URLField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "contract_type",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "experience_level",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("work_type", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "applications_count",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("posted_time", models.CharField(blank=True, max_length=64, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("salary", models.CharField(blank=True, max_length=128, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("job_url", models.URLField()),
                ("apply_type", models.CharField(max_length=32)),
            ],
            options={
                "verbose_name": "Job",
                "verbose_name_plural": "Jobs",
                "ordering": ["-published_at"],
            },
        ),
    ]
