"""workspace

Revision ID: 0002_workspace
Revises: 0001_foundation
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0002_workspace"
down_revision: str | None = "0001_foundation"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


TABLES = (
    "actors",
    "tasks",
    "audit_events",
    "artifacts",
    "blobs",
    "artifact_versions",
    "document_types",
    "documents",
    "artifact_reviews",
    "artifact_derivations",
    "source_records",
    "evidence_claims",
    "task_artifacts",
    "task_evidence",
    "agent_runs",
    "browser_devices",
    "browser_snapshots",
    "browser_commands",
    "candidate_profiles",
    "companies",
    "contacts",
    "jobs",
    "opportunities",
    "request_receipts",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_runs",
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("profile", sa.String(length=100), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("config_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("checkpoint", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("output", sa.Text(), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("lease_id", sa.Uuid(), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("row_version", sa.Integer(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "state IN ('queued', 'running', 'completed', 'failed', 'cancelled')",
            name=op.f("ck_agent_runs_state"),
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["actors.id"], name=op.f("fk_agent_runs_owner_id_actors")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_runs")),
    )
    op.create_index(op.f("ix_agent_runs_owner_id"), "agent_runs", ["owner_id"], unique=False)
    op.create_index(op.f("ix_agent_runs_state"), "agent_runs", ["state"], unique=False)
    op.create_table(
        "browser_devices",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("pairing_digest", sa.String(length=64), nullable=True),
        sa.Column("pairing_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("token_digest", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("paired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["actors.id"], name=op.f("fk_browser_devices_owner_id_actors")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_browser_devices")),
        sa.UniqueConstraint("id", "owner_id", name=op.f("uq_browser_devices_id")),
        sa.UniqueConstraint("pairing_digest", name=op.f("uq_browser_devices_pairing_digest")),
        sa.UniqueConstraint("token_digest", name=op.f("uq_browser_devices_token_digest")),
    )
    op.create_index(
        op.f("ix_browser_devices_owner_id"), "browser_devices", ["owner_id"], unique=False
    )
    op.create_table(
        "candidate_profiles",
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("headline", sa.String(length=300), nullable=False),
        sa.Column("location", sa.String(length=200), nullable=False),
        sa.Column("timezone", sa.String(length=100), nullable=False),
        sa.Column("preferences", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("row_version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["actors.id"], name=op.f("fk_candidate_profiles_actor_id_actors")
        ),
        sa.PrimaryKeyConstraint("actor_id", name=op.f("pk_candidate_profiles")),
    )
    op.create_table(
        "companies",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("domain", sa.String(length=253), nullable=True),
        sa.Column("industry", sa.String(length=150), nullable=True),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("row_version", sa.Integer(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("length(trim(name)) > 0", name=op.f("ck_companies_name")),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["actors.id"], name=op.f("fk_companies_owner_id_actors")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_companies")),
        sa.UniqueConstraint("id", "owner_id", name=op.f("uq_companies_id")),
    )
    op.create_index(op.f("ix_companies_owner_id"), "companies", ["owner_id"], unique=False)
    op.create_table(
        "request_receipts",
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.Uuid(), nullable=False),
        sa.Column("operation", sa.String(length=300), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("response", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["actors.id"], name=op.f("fk_request_receipts_actor_id_actors")
        ),
        sa.PrimaryKeyConstraint("actor_id", "key", name=op.f("pk_request_receipts")),
    )
    op.create_table(
        "browser_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("device_id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("origin", sa.String(length=500), nullable=False),
        sa.Column("page_url", sa.Text(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("fields", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id", "owner_id"],
            ["browser_devices.id", "browser_devices.owner_id"],
            name=op.f("fk_browser_snapshots_device_id_browser_devices"),
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["actors.id"], name=op.f("fk_browser_snapshots_owner_id_actors")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_browser_snapshots")),
        sa.UniqueConstraint("id", "device_id", "owner_id", name=op.f("uq_browser_snapshots_id")),
    )
    op.create_index(
        op.f("ix_browser_snapshots_device_id"), "browser_snapshots", ["device_id"], unique=False
    )
    op.create_index(
        op.f("ix_browser_snapshots_owner_id"), "browser_snapshots", ["owner_id"], unique=False
    )
    op.create_table(
        "contacts",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("company_id", sa.Uuid(), nullable=True),
        sa.Column("linkedin_url", sa.Text(), nullable=True),
        sa.Column("relationship", sa.String(length=20), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("row_version", sa.Integer(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "relationship IN ('new', 'connected', 'warm', 'advocate')",
            name=op.f("ck_contacts_relationship"),
        ),
        sa.CheckConstraint("length(trim(name)) > 0", name=op.f("ck_contacts_name")),
        sa.ForeignKeyConstraint(
            ["company_id", "owner_id"],
            ["companies.id", "companies.owner_id"],
            name=op.f("fk_contacts_company_id_companies"),
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["actors.id"], name=op.f("fk_contacts_owner_id_actors")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contacts")),
        sa.UniqueConstraint("id", "owner_id", name=op.f("uq_contacts_id")),
    )
    op.create_index(op.f("ix_contacts_company_id"), "contacts", ["company_id"], unique=False)
    op.create_index(op.f("ix_contacts_owner_id"), "contacts", ["owner_id"], unique=False)
    op.create_table(
        "jobs",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column("work_mode", sa.String(length=20), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("salary_min", sa.Integer(), nullable=True),
        sa.Column("salary_max", sa.Integer(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("row_version", sa.Integer(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status IN ('open', 'closed', 'unknown')", name=op.f("ck_jobs_status")),
        sa.CheckConstraint(
            "work_mode IN ('remote', 'hybrid', 'onsite', 'unspecified')",
            name=op.f("ck_jobs_work_mode"),
        ),
        sa.CheckConstraint(
            "salary_max IS NULL OR salary_max >= COALESCE(salary_min, 0)",
            name=op.f("ck_jobs_salary_max"),
        ),
        sa.CheckConstraint(
            "salary_min IS NULL OR salary_min >= 0", name=op.f("ck_jobs_salary_min")
        ),
        sa.ForeignKeyConstraint(
            ["company_id", "owner_id"],
            ["companies.id", "companies.owner_id"],
            name=op.f("fk_jobs_company_id_companies"),
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["actors.id"], name=op.f("fk_jobs_owner_id_actors")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
        sa.UniqueConstraint("id", "company_id", "owner_id", name=op.f("uq_jobs_id_company_owner")),
        sa.UniqueConstraint("id", "owner_id", name=op.f("uq_jobs_id_owner")),
        sa.UniqueConstraint("owner_id", "source_url", name=op.f("uq_jobs_owner_id")),
    )
    op.create_index(op.f("ix_jobs_company_id"), "jobs", ["company_id"], unique=False)
    op.create_index(op.f("ix_jobs_owner_id"), "jobs", ["owner_id"], unique=False)
    op.create_table(
        "browser_commands",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("device_id", sa.Uuid(), nullable=False),
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("fields", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("state", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "state IN ('pending', 'claimed', 'applied', 'rejected', 'failed', 'outcome_unknown')",
            name=op.f("ck_browser_commands_state"),
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["actors.id"], name=op.f("fk_browser_commands_owner_id_actors")
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id", "device_id", "owner_id"],
            ["browser_snapshots.id", "browser_snapshots.device_id", "browser_snapshots.owner_id"],
            name=op.f("fk_browser_commands_snapshot_id_browser_snapshots"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_browser_commands")),
    )
    op.create_index(
        op.f("ix_browser_commands_device_id"), "browser_commands", ["device_id"], unique=False
    )
    op.create_index(
        op.f("ix_browser_commands_owner_id"), "browser_commands", ["owner_id"], unique=False
    )
    op.create_table(
        "opportunities",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=True),
        sa.Column("contact_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("stage", sa.String(length=20), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("row_version", sa.Integer(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "stage IN ('researching', 'preparing', 'applied', 'interviewing', 'offer', 'closed')",
            name=op.f("ck_opportunities_stage"),
        ),
        sa.CheckConstraint("priority BETWEEN 0 AND 3", name=op.f("ck_opportunities_priority")),
        sa.ForeignKeyConstraint(
            ["company_id", "owner_id"],
            ["companies.id", "companies.owner_id"],
            name=op.f("fk_opportunities_company_id_companies"),
        ),
        sa.ForeignKeyConstraint(
            ["contact_id", "owner_id"],
            ["contacts.id", "contacts.owner_id"],
            name=op.f("fk_opportunities_contact_id_contacts"),
        ),
        sa.ForeignKeyConstraint(
            ["job_id", "company_id", "owner_id"],
            ["jobs.id", "jobs.company_id", "jobs.owner_id"],
            name=op.f("fk_opportunities_job_id_jobs"),
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["actors.id"], name=op.f("fk_opportunities_owner_id_actors")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_opportunities")),
        sa.UniqueConstraint("id", "owner_id", name=op.f("uq_opportunities_id")),
        sa.UniqueConstraint("owner_id", "job_id", name=op.f("uq_opportunities_owner_id")),
    )
    op.create_index(
        op.f("ix_opportunities_company_id"), "opportunities", ["company_id"], unique=False
    )
    op.create_index(op.f("ix_opportunities_job_id"), "opportunities", ["job_id"], unique=False)
    op.create_index(op.f("ix_opportunities_owner_id"), "opportunities", ["owner_id"], unique=False)
    op.create_index(op.f("ix_opportunities_stage"), "opportunities", ["stage"], unique=False)
    op.add_column("actors", sa.Column("auth_subject", sa.String(length=500), nullable=True))
    op.create_unique_constraint(op.f("uq_actors_auth_subject"), "actors", ["auth_subject"])
    op.add_column("tasks", sa.Column("opportunity_id", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_tasks_opportunity_id"), "tasks", ["opportunity_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_tasks_opportunity_id_opportunities"),
        "tasks",
        "opportunities",
        ["opportunity_id", "owner_id"],
        ["id", "owner_id"],
    )
    # ### end Alembic commands ###

    # Access goes through FastAPI. Supabase anon/authenticated roles get no policy.
    # The trusted API connects as the schema owner (or an explicitly granted role).
    for table in TABLES:
        op.execute(sa.text(f'ALTER TABLE "{table}" ENABLE ROW LEVEL SECURITY'))
    from uuid import NAMESPACE_URL, uuid5

    document_types = sa.table(
        "document_types",
        sa.column("id", sa.Uuid()),
        sa.column("slug", sa.String()),
        sa.column("name", sa.String()),
    )
    for slug, name in [
        ("resume", "Resume"),
        ("cover-letter", "Cover letter"),
        ("research", "Research brief"),
        ("interview", "Interview brief"),
        ("notes", "Notes"),
    ]:
        op.execute(
            sa.dialects.postgresql.insert(document_types)
            .values(
                id=uuid5(NAMESPACE_URL, "command-center:document-type:" + slug),
                slug=slug,
                name=name,
            )
            .on_conflict_do_nothing(index_elements=["slug"])
        )


def downgrade() -> None:
    for table in TABLES:
        op.execute(sa.text(f'ALTER TABLE "{table}" DISABLE ROW LEVEL SECURITY'))
    # Keep document types: foundation documents may reference them.

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_tasks_opportunity_id_opportunities"), "tasks", type_="foreignkey")
    op.drop_index(op.f("ix_tasks_opportunity_id"), table_name="tasks")
    op.drop_column("tasks", "opportunity_id")
    op.drop_constraint(op.f("uq_actors_auth_subject"), "actors", type_="unique")
    op.drop_column("actors", "auth_subject")
    op.drop_index(op.f("ix_opportunities_stage"), table_name="opportunities")
    op.drop_index(op.f("ix_opportunities_owner_id"), table_name="opportunities")
    op.drop_index(op.f("ix_opportunities_job_id"), table_name="opportunities")
    op.drop_index(op.f("ix_opportunities_company_id"), table_name="opportunities")
    op.drop_table("opportunities")
    op.drop_index(op.f("ix_browser_commands_owner_id"), table_name="browser_commands")
    op.drop_index(op.f("ix_browser_commands_device_id"), table_name="browser_commands")
    op.drop_table("browser_commands")
    op.drop_index(op.f("ix_jobs_owner_id"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_company_id"), table_name="jobs")
    op.drop_table("jobs")
    op.drop_index(op.f("ix_contacts_owner_id"), table_name="contacts")
    op.drop_index(op.f("ix_contacts_company_id"), table_name="contacts")
    op.drop_table("contacts")
    op.drop_index(op.f("ix_browser_snapshots_owner_id"), table_name="browser_snapshots")
    op.drop_index(op.f("ix_browser_snapshots_device_id"), table_name="browser_snapshots")
    op.drop_table("browser_snapshots")
    op.drop_table("request_receipts")
    op.drop_index(op.f("ix_companies_owner_id"), table_name="companies")
    op.drop_table("companies")
    op.drop_table("candidate_profiles")
    op.drop_index(op.f("ix_browser_devices_owner_id"), table_name="browser_devices")
    op.drop_table("browser_devices")
    op.drop_index(op.f("ix_agent_runs_state"), table_name="agent_runs")
    op.drop_index(op.f("ix_agent_runs_owner_id"), table_name="agent_runs")
    op.drop_table("agent_runs")
    # ### end Alembic commands ###
