"""memory

Revision ID: 0003_memory
Revises: 0002_workspace
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0003_memory"
down_revision: str | None = "0002_workspace"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "memory_items",
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("row_version", sa.Integer(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("kind IN ('note', 'preference')", name=op.f("ck_memory_items_kind")),
        sa.CheckConstraint("source IN ('human', 'agent')", name=op.f("ck_memory_items_source")),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["actors.id"], name=op.f("fk_memory_items_owner_id_actors")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memory_items")),
    )
    op.create_index(op.f("ix_memory_items_owner_id"), "memory_items", ["owner_id"], unique=False)
    op.execute("ALTER TABLE memory_items ENABLE ROW LEVEL SECURITY")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_memory_items_owner_id"), table_name="memory_items")
    op.drop_table("memory_items")
    # ### end Alembic commands ###
