"""Migrate legacy web settings into root .env and generate a minimal web projection."""

import argparse
import os
import tempfile
from pathlib import Path

from dotenv import dotenv_values

ROOT = Path(__file__).resolve().parents[1]
WEB_KEYS = (
    "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY",
    "CLERK_SECRET_KEY",
    "NEXT_PUBLIC_CLERK_SIGN_IN_URL",
    "NEXT_PUBLIC_CLERK_SIGN_UP_URL",
    "NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL",
    "NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL",
    "CC_API_URL",
    "CC_WEB_ORIGIN",
)
HEADER = "# Generated by make env-sync from root .env; edit root .env only.\n"


def quote(value: str) -> str:
    return "'" + value.replace("\\", "\\\\").replace("'", "\\'") + "'"


def write_private(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary = tempfile.mkstemp(dir=path.parent)
    try:
        with os.fdopen(fd, "w") as stream:
            stream.write(content)
        os.replace(temporary, path)
    finally:
        Path(temporary).unlink(missing_ok=True)


def sync(root: Path = ROOT, *, check: bool = False) -> None:
    source = root / ".env"
    values = dict(dotenv_values(source, interpolate=False))
    if not source.exists():
        raise ValueError("Run make setup to create root .env first.")
    defaults = dotenv_values(root / ".env.example", interpolate=False)
    content = source.read_text()
    legacy = []
    for name in (
        ".env",
        ".env.local",
        ".env.development",
        ".env.development.local",
        ".env.production",
        ".env.production.local",
    ):
        path = root / "apps/web" / name
        if not path.exists() or path.read_text().startswith(HEADER):
            continue
        legacy.append(path)
        for key, value in dotenv_values(path, interpolate=False).items():
            if not value:
                continue
            if key not in defaults:
                raise ValueError(f"Move {key} from {path.name} to root .env manually.")
            if values.get(key) and values[key] != value:
                raise ValueError(
                    f"Conflicting {key} in root and web environment; reconcile first."
                )
            if not values.get(key):
                values[key] = value
                # Last assignment wins for dotenv and Compose. No credentials are logged.
                content += f"\n{key}={quote(value)}\n"
    for key in WEB_KEYS:
        if key not in values:
            values[key] = defaults.get(key) or ""
            content += f"\n{key}={quote(values[key] or '')}\n"
    generated = HEADER + "".join(
        f"{key}={quote(values.get(key) or '')}\n" for key in WEB_KEYS
    )
    destination = root / "apps/web/.env.local"
    if check:
        if legacy or not destination.exists() or destination.read_text() != generated:
            raise ValueError("Web environment is stale; run make env-sync.")
        return
    if content != source.read_text():
        write_private(source, content)
    write_private(destination, generated)
    for path in legacy:
        if path != destination:
            path.unlink()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        sync(check=args.check)
    except ValueError as exc:
        raise SystemExit(str(exc)) from None
    print("Web environment checked." if args.check else "Web environment synchronized.")
